version: '3.7'
services:
  master:
    container_name: master
    build: ./
    ports:
      - 8080:8080
      - 3307:3307
      - 80:80  
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - ../app/:/root/app
    restart: always
